name: Integration Test
on:
  workflow_dispatch:

jobs:
  integration-test:
    environment: integration
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
      - name: Integration tests
        run: ./gradlew integration-test
        env:
          S2_ACCESS_TOKEN: ${{ secrets.S2_ACCESS_TOKEN }}
          S2_BASIN: ${{ secrets.S2_BASIN }}
